### ISSUE TITLE
Requisitos insuficientes del trabajo

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-losalex#1]
Hola:

Estoy revisando el menú que habéis subido y los objetivos. Según está planteado, de manera muy escueta, no sé ver el alcance del proyecto. Tenéis que cumplir todos los requisitos que os pedimos y tenéis en Moodle (como el uso de vectores de estructuras). Por favor, revisadlo, ampliad la descripción y avisadme. Cuando lo hagáis entonces podré plantearos algún hito para que lo entreguéis el 20 de abril.

Una última cosa, el fichero C debe tener extensión .c y el vuestro no lo tiene.

Un saludo.

**Comment by alejandromartinherreros** [comment]
Si perdona, ya está corregido.
